##Importing Libraries

In [268]:
import numpy as np
import math
axis = np.array([1/3, 1/3, 1/3])**(1/2)
angle = math.pi/3

## Rodrigues formula

In [269]:
def rodrigues(axis, angle):
    """
    Rodrigues formula for rotating a point around an axis by a given angle.
    """
    axis = np.asarray(axis)
    axis = axis / np.sqrt(np.dot(axis, axis))
    a = np.cos(angle / 2.0)
    b, c, d = -axis * np.sin(angle / 2.0)
    aa, bb, cc, dd = a * a, b * b, c * c, d * d
    bc, ad, ac, ab, bd, cd = b * c, a * d, a * c, a * b, b * d, c * d
    return np.array([[aa + bb - cc - dd, 2 * (bc + ad), 2 * (bd - ac)],
                     [2 * (bc - ad), aa + cc - bb - dd, 2 * (cd + ab)],
                     [2 * (bd + ac), 2 * (cd - ab), aa + dd - bb - cc]])
# This function takes an axis of rotation (a 3D vector) and an angle of rotation (in radians) as inputs, and returns a 3x3 rotation matrix that can be used to rotate a point around the given axis by the specified angle.

# For example, you can use this function as follows:

# Copy code
# Rotate a point (1, 0, 0) around the y-axis by 90 degrees


#### If v is a vector in ℝ3 and k is a unit vector describing an axis of rotation about which v rotates by an angle θ according to the right hand rule, the Rodrigues formula for the rotated vector vrot is

In [270]:
##Rotation matrix
R = rodrigues(axis, angle)
print(R)

[[ 0.66666667 -0.33333333  0.66666667]
 [ 0.66666667  0.66666667 -0.33333333]
 [-0.33333333  0.66666667  0.66666667]]


In [271]:
!pip install openmesh

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


## Reading Obj file

In [272]:
import openmesh as om
mesh_2 = om.read_trimesh("/content/cube.obj")
point_array = mesh_2.points()

## Printing Coordinates of vertex

In [273]:
point_array


array([[ 1.,  1., -1.],
       [ 1., -1., -1.],
       [ 1.,  1.,  1.],
       [ 1., -1.,  1.],
       [-1.,  1., -1.],
       [-1., -1., -1.],
       [-1.,  1.,  1.],
       [-1., -1.,  1.]])

In [275]:
p_prime = point_array
print(p_prime)

[[ 1.  1. -1.]
 [ 1. -1. -1.]
 [ 1.  1.  1.]
 [ 1. -1.  1.]
 [-1.  1. -1.]
 [-1. -1. -1.]
 [-1.  1.  1.]
 [-1. -1.  1.]]


In [276]:
p_prime.shape

(8, 3)

##Applying Rotation on each coordinate of cube

In [277]:
point_array[0] = np.matmul(R,point_array[0])
point_array[1] = np.matmul(R,point_array[1])
point_array[2] = np.matmul(R,point_array[2])
point_array[3] = np.matmul(R,point_array[3])
point_array[4] = np.matmul(R,point_array[4])
point_array[5] = np.matmul(R,point_array[5])
point_array[6] = np.matmul(R,point_array[6])
point_array[7] = np.matmul(R,point_array[7])

In [278]:
##Writing New Mesh file
om.write_mesh('cube_2.obj', mesh_2)

In [279]:
point_array

array([[-0.33333333,  1.66666667, -0.33333333],
       [ 0.33333333,  0.33333333, -1.66666667],
       [ 1.        ,  1.        ,  1.        ],
       [ 1.66666667, -0.33333333, -0.33333333],
       [-1.66666667,  0.33333333,  0.33333333],
       [-1.        , -1.        , -1.        ],
       [-0.33333333, -0.33333333,  1.66666667],
       [ 0.33333333, -1.66666667,  0.33333333]])

In [280]:
q_prime = point_array
print(q_prime)

[[-0.33333333  1.66666667 -0.33333333]
 [ 0.33333333  0.33333333 -1.66666667]
 [ 1.          1.          1.        ]
 [ 1.66666667 -0.33333333 -0.33333333]
 [-1.66666667  0.33333333  0.33333333]
 [-1.         -1.         -1.        ]
 [-0.33333333 -0.33333333  1.66666667]
 [ 0.33333333 -1.66666667  0.33333333]]


In [281]:
q_prime_t = np.transpose(q_prime)

In [282]:
q_prime_t.shape

(3, 8)

## Formula Used

*   S = q_prime_transpose . p_prime
*   U, sigma, V = SVD(S)


*   R = V . U_transpose
*   U,V are orthogonal

*   Determinant(R) = +1 , means rotation
*   Determinant(R) = -1 , means reflection
R = Rotation matrix, q_prime = rotated relative position,
p_prime = actual relative position,
p,q = actual coodinates of vertices of cube before and after rotatio respectively.

In [283]:
## S = q'_transpose * p'
S = np.matmul(q_prime_t,p_prime)

In [284]:
S

array([[8.00000000e+00, 4.74928738e-16, 6.32210333e-17],
       [4.74928738e-16, 8.00000000e+00, 3.63906436e-16],
       [6.32210333e-17, 3.63906436e-16, 8.00000000e+00]])

In [285]:
##Taking SVD of S
U,sigma,V = np.linalg.svd(S)

In [286]:
R_new = np.matmul(V,np.transpose(U))

In [287]:
R_new

array([[ 9.91255986e-01,  1.74115697e-02, -1.30799109e-01],
       [-5.98897693e-17,  9.91255986e-01,  1.31952907e-01],
       [ 1.31952907e-01, -1.30799109e-01,  9.82588430e-01]])

In [288]:
diff = R-R_new

In [289]:
diff

array([[-0.32458932, -0.3507449 ,  0.79746578],
       [ 0.66666667, -0.32458932, -0.46528624],
       [-0.46528624,  0.79746578, -0.31592176]])

In [290]:
## Taking Determinant
print(np.linalg.det(R))

1.0


In [291]:
## Taking Determinant
print(np.linalg.det(R_new))

0.9999999999999998


In [292]:
##Adding Gaussian noise in q_prime
import random
temp = random.gauss(0, 0.5**0.5)
q_prime_noise = q_prime+temp

In [293]:
##Adding Noise in point q_prime 0
q_prime_noise[0]+=5

In [294]:
p_prime.shape

(8, 3)

In [295]:
q_prime_noise.shape

(8, 3)

In [296]:
s_n = np.matmul(np.transpose(q_prime_noise),p_prime)

In [297]:
s_n

array([[ 6.33333333,  8.33333333, -1.66666667],
       [-1.66666667, 16.33333333, -1.66666667],
       [-1.66666667,  8.33333333,  6.33333333]])

In [298]:
U_n,sig_n,V_n = np.linalg.svd(s_n)

In [299]:
R_noise = np.matmul(V_n,np.transpose(U_n))
print(R_noise)

[[-0.67603014  0.00646516  0.73684561]
 [ 0.10512639 -0.98888669  0.10512639]
 [ 0.72933647  0.14853053  0.66783755]]


In [300]:
print(R_new-R_noise)

[[ 1.66728613  0.01094641 -0.86764472]
 [-0.10512639  1.98014268  0.02682652]
 [-0.59738357 -0.27932964  0.31475088]]


In [301]:
##Determinant of Noisy rotation matrix
det_R_noise = np.linalg.det(R_noise)

In [302]:
det_R_noise

1.0000000000000013